# Этап сборки фронтенда
FROM node:20-alpine AS build
WORKDIR /app
# копируем зависимости из поддиректории frontend
COPY frontend/package*.json ./frontend/
WORKDIR /app/frontend
RUN npm install
# копируем весь код фронтенда
COPY frontend/ .
RUN npm run build

# Этап запуска
FROM nginx:stable-alpine
COPY --from=build /app/frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]